    <div class="left">
      <a href="http://www.suckless.org">home</a> |
      <a href="http://code.suckless.org/hg">code</a> |
      <a href="http://www.suckless.org/dl">download</a> |
      <a href="http://dwm.suckless.org">dwm</a> |
      <a href="http://libs.suckless.org">libs</a> |
      <a href="http://tools.suckless.org">tools</a> |
      <a href="http://wmii.suckless.org">wmii</a> |
      <a href="http://wmi.suckless.org">wmi</a>
    </div>

    <div class="right">
      <span class="doNotDisplay">Related sites:</span>
      <!-- | <a href="http://garbe.us/update_log">site updates</a> | -->
      <a href="/sitemap">site map</a>
    </div>

