    <ul>
      <li><a href="http://suckless.org">home/</a></li>
      <li><a href="http://hg.suckless.org">code</a></li>
      <li><a href="http://dl.suckless.org">download</a></li>
      <li><a href="http://man.suckless.org">man/</a></li>
      <li><a href="http://dwm.suckless.org">dwm/</a></li>
      <li><a href="http://libs.suckless.org">libs/</a></li>
      <li><a href="http://st.suckless.org">st</a></li>
      <li><a href="http://surf.suckless.org">surf</a></li>
      <li><a href="http://tools.suckless.org">tools/</a></li>
      <li><a class="thisPage" href="http://wmii.suckless.org">wmii/</a></li>
      <li><a href="http://wmi.suckless.org">wmi/</a></li>
    </ul>
