<div class="left">
      <a href="http://werc.cat-v.org/">Powered by werc</a>
</div>
<div class="right">
    <style type="text/css">
    @import url(http://www.google.com/cse/api/branding.css);
    </style>
    <div class="cse-branding-bottom">
        <div class="cse-branding-form">
            <form action="http://www.google.com/cse" id="cse-search-box">
            <div>
                <input type="hidden" name="cx" value="001621472792195143094:yaf_hfror00" />
                <input type="hidden" name="ie" value="UTF-8" />
                <input type="text" name="q" size="31" />
                <input type="submit" name="sa" value="Search" />
            </div>
            </form>
        </div>
    </div>
</div>
