<br class="doNotDisplay doNotPrint" />

<div class="left">
      <a href="http://werc.cat-v.org/">Powered by werc</a>
</div>
<div class="right">
<form action="http://www.google.com/cse" id="cse-search-box" style="display: in
line">
  <div style="display: inline">
  <input type="hidden" name="cx" value="001621472792195143094:yaf_hfror00"/>
  <input type="hidden" name="ie" value="UTF-8" />
  <input type="text" name="q" size="32" />
  <input type="submit" name="sa" value="Search" />
  </div>
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box"></script>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4071820-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
