    <div class="left">
      <a href="http://suckless.org">home</a> &nbsp;
      <a href="http://hg.suckless.org">code</a> &nbsp;
      <a href="http://dl.suckless.org">download</a> &nbsp;
      <a href="http://dwm.suckless.org">dwm</a> &nbsp;
      <a href="http://libs.suckless.org">libs</a> &nbsp;
      <a href="http://st.suckless.org">st</a> &nbsp;
      <a href="http://surf.suckless.org">surf</a> &nbsp;
      <a href="http://tools.suckless.org">tools</a> &nbsp;
      <a href="http://wmii.suckless.org">wmii</a> &nbsp;
      <a href="http://wmi.suckless.org">wmi</a>
    </div>

    <div class="right">
      <span class="doNotDisplay">Related sites:</span>
      <!-- | <a href="http://garbe.us/update_log">site updates</a> | -->
      <a href="/sitemap">site map</a>
    </div>

