    <div class="left">
      <a href="http://suckless.org">home</a> &nbsp;
      <a href="http://hg.suckless.org">code</a> &nbsp;
      <a href="http://dl.suckless.org">download</a> &nbsp;
      <a href="http://man.suckless.org">man</a> &nbsp;
      <a href="http://dwm.suckless.org">dwm</a> &nbsp;
      <a href="http://libs.suckless.org">libs</a> &nbsp;
      <a href="http://st.suckless.org">st</a> &nbsp;
      <a href="http://surf.suckless.org">surf</a> &nbsp;
      <a href="http://tools.suckless.org">tools</a> &nbsp;
      <a href="http://wmii.suckless.org">wmii</a> &nbsp;
      <a href="http://wmi.suckless.org">wmi</a>
    </div>

    <div class="right">
      <span class="doNotDisplay">Related sites:</span>
      <a href="/sitemap">site map</a>
      <!-- AddThis Button BEGIN -->
      <a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4a9e7bf65546d320"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js?pub=xa-4a9e7bf65546d320"></script>
      <!-- AddThis Button END -->
    </div>

