<div class="left"><a href="http://werc.cat-v.org/">Powered by werc</a></div>
<!-- TODO Maybe should add a programatically generated google search box -->
<!-- <div class="right"><a href="/_users/login">User Login</div> -->

<br />
<br class="doNotDisplay doNotPrint" />

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4071820-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>

